language: java
os: linux
jdk: openjdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

before_install:
  - wget http://mirrors.ae-online.de/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar xf apache-maven-3.3.9-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH

script:
-  set -e
-  export PING_SLEEP=30s
-  export WORKDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-  export BUILD_OUTPUT=$WORKDIR/build.out
-  touch $BUILD_OUTPUT
-  dump_output() {
-  tail -500 $BUILD_OUTPUT -  }

- error_handler() {
-    dump_output
-    exit 1-  }
-  trap 'error_handler' ERR


-  bash -c "while true; do echo \$(date) - building ...; sleep $PING_SLEEP; done" &
-  PING_LOOP_PID=$!

-  mvn clean install -Pjacoco >> $BUILD_OUTPUT 2>&1

-  dump_output
-  kill $PING_LOOP_PID

after_success:
  - mvn jacoco:report coveralls:report