version: '3.3'

services:
  fuse:
    image: yangdb/yang.db:latest
    ports:
      - 8888:8888
    environment:
      - "ELASTICSEARCH_HOST=es"
      - "ELASTICSEARCH_CLUSTER_NAME=Knowledge"
    networks:
      - network
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=es-master"
      - "node.master=false"
      - "node.data=false"
      - "node.ingest=false"
      - "network.publish_host=127.0.0.1"
      - "cluster.name=Knowledge"
    networks:
      - network
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: 'global'

  es-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "ES_JAVA_OPTS=-Xms7g -Xmx7g"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=es-master"
      - "node.master=true"
      - "node.data=false"
      - "node.ingest=false"
      - "cluster.name=Knowledge"
    networks:
      - network
    deploy:
      endpoint_mode: dnsrr
      mode: 'replicated'
      replicas: 3
  es-data:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "ES_JAVA_OPTS=-Xms13g -Xmx13g"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.zen.ping.unicast.hosts=es-master"
      - "node.master=false"
      - "node.data=true"
      - "node.ingest=false"
      - "cluster.name=Knowledge"
    volumes:
      - es-fuse-data:/usr/share/elasticsearch/data
    networks:
      - network
    deploy:
      endpoint_mode: dnsrr
      mode: 'global'

volumes:
  es-fuse-data:
    driver: local
  es-fuse-master-data2:
    driver: local

networks:
  network:
    driver: overlay
    attachable: true