version: '3.3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.type=single-node"
      - "network.publish_host=127.0.0.1"
      - "cluster.name=${ELASTICSEARCH_CLUSTER_NAME}"
    networks:
      - network
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
      - target: 9300
        published: 9300
        protocol: tcp
        mode: host
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    links:
      - es
    depends_on:
      - es
    ports:
      - 5601:5601
    networks:
      - network
  fuse:
    image: yangdb/yang.db:latest
    depends_on:
      - es
    ports:
      - 8888:8888
    environment:
      - "elasticsearchHosts=localhost"
      - "elasticsearchClusterName=${ELASTICSEARCH_CLUSTER_NAME}"
    volumes:
      - fuse-data:/usr/share/fuse
    networks:
      - network

volumes:
  fuse-data:
    driver: local
  esdata1:
    driver: local

networks:
  network:
    attachable: true